### ISSUE TITLE
Здесь нет синтаксической ошибки.

### ISSUE THREAD

**Issue by andrey-ilyin** [NoMercyLS/bulatnikov-backend#4]
https://github.com/NoMercyLS/bulatnikov-backend/blob/b9f302084785cda1b947e96ebeac9b8f8d55c389/LW1/LW1.txt#L46

**Comment by NoMercyLS** [comment]
Строку удалил, но с тем, что нет синтаксической ошибки нет - не согласен. Изначальный запрос составлен некорректно, содержит в себе синтаксическую ошибку(вместо hard там написано hardly, что и является синтаксической ошибкой). 
Также [на ресурсе](https://airbrake.io/blog/http-errors/400-bad-request), которым я пользовался, было написана именно такая информация.
Цитата:

> The 400 Bad Request Error is an HTTP response status code that indicates that the server was unable to process the request sent by the client due to **invalid syntax**.

Считаю ошибку исправленной.

**Comment by NoMercyLS** [comment]
Fixed
